name: Publish

on:
  push:
    branches: [main]
    paths: "**/Cargo.toml"

jobs:
  Publish:
    if: github.repository_owner == 'mlm-games'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # ensure crate order
      fail-fast: false
      matrix:
        crate:
          - { name: "rndk", target: "x86_64-unknown-linux-gnu" }
          - { name: "cargo-rapk", target: "x86_64-unknown-linux-gnu" }
    steps:
      - uses: actions/checkout@v4
      - name: Publish ${{ matrix.crate.name }}
        continue-on-error: true
        run: cargo publish --manifest-path ${{ matrix.crate.name }}/Cargo.toml --target ${{ matrix.crate.target }} --token ${{ secrets.cratesio_token }}
